### ISSUE TITLE
Create announcement and comment entities

### ISSUE THREAD

**Issue by nsanaie** [comp423-24s/comp423-24s.github.io#1]
## Task
Create SQLAlchemy entities that correspond to the announcement and comment pydantic models in the backend.

## User Persona
**Randy Random can view all public announcements on the CSXL website without being logged into an account.**

## Overall User Story
**Story A: As Randy Random, I want to load up the CSXL website to see the latest news and announcements in an Announcements tab.**

## Why
- We need a entity that models the structure of our data in the database.

## Acceptance Criteria
- [ ] Create the announcement and comment entities.
- [ ] Include all required fields from the respective pydantic models.
- [ ] Establish a one-to-many relationship between announcements and comments.
