### ISSUE TITLE
Sprint02 review

### ISSUE THREAD

**Issue by nsanaie** [comp423-24s/comp423-24s.github.io#2]
## Task
**Review and wrap up sprint 02**

## Acceptance Criteria
- [ ] Verify the functionality of all old and new backend methods.
- [ ] Make sure all unit tests are written and pass.
- [ ] Ensure no console logs or errors are being outputted when using the frontend.
- [ ] Ensure all announcement styling is uniform with the CSXL site.
- [ ] Add a lot of new dummy data!
